$schema: https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/v0.23.2/schema/markdownlint-cli2-config-schema.json
gitignore: true
globs:
  - "**/*.md"
config:
  $schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/v0.41.1/schema/markdownlint-config-schema.json
  first-line-h1: false
  line-length: false
  ol-prefix:
    style: ordered
